name: Java Spring Boot CI TaxHub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_USERNAME: ${{ secrets.USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.PASSWORD }}
      SPRING_DIALECT: ${{ secrets.DIALECT }}
      SPRING_URL: ${{ secrets.URL }}
      SPRING_DDL: ${{ secrets.DDL }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build com Maven
        run: mvn -B clean install

      - name: Run Testes Unitários
        run: mvn test
  deploy:
    name: Build Docker + Push ECR + Redeploy ECS
    runs-on: ubuntu-latest
    needs: build-and-test

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
            aws-region: us-east-1
      - name: Testar acesso AWS
        run: aws sts get-caller-identity

      - name: Login no Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ----------.dkr.ecr.us-east-1.amazonaws.com
      - name: Build Imagem Docker
        run:
          docker build -t taxhub-app:latest .
      - name: Tag e push da imagem para ECR
        run: |
          docker tag taxhub-app:latest 590184085974.dkr.ecr.us-east-1.amazonaws.com/taxhub-app:latest
          docker push 590184085974.dkr.ecr.us-east-1.amazonaws.com/taxhub-app:latest
      - name: Redeploy ECS Service
        run: |
          aws ecs update-service \
          --cluster cluster \
          --service service \
          --force-new-deployment

          